import Foundation

/// The project's derived animation atlas (`khosrow.runtime.json`).
///
/// Combines the untouched `pet.json` identity with the empirically-derived grid,
/// the inferred animation clips, and the Claude-Code state map. Generated by
/// `scripts/build_runtime_manifest.py`; consumed by the app and the tests.
public struct RuntimeManifest: Codable, Equatable {

    public struct Pet: Codable, Equatable {
        public let id: String
        public let displayName: String
        public let description: String?
        public let spriteVersionNumber: Int
        public let spritesheetPath: String
    }

    public struct Sheet: Codable, Equatable {
        public let originalWebP: String
        public let runtimePNG: String
        public let width: Int
        public let height: Int
        public let cols: Int
        public let rows: Int
        public let cellWidth: Int
        public let cellHeight: Int
        public let contentTopPad: Int
        public let contentBottomPad: Int
        public let anchor: String
    }

    public struct Clip: Codable, Equatable {
        public let id: String
        public let row: Int
        public let frameCount: Int
        public let facing: String
        public let fps: Double
        public let loop: Bool
        public let description: String?
    }

    public struct StateBinding: Codable, Equatable {
        public let state: String
        public let clip: String
        public let fpsOverride: Double?
        public let dim: Bool
        public let rationale: String?
    }

    public let schemaVersion: Int
    public let pet: Pet
    public let sheet: Sheet
    public let defaultState: String
    public let clips: [String: Clip]
    public let states: [String: StateBinding]

    public static func decode(from data: Data) throws -> RuntimeManifest {
        try JSONDecoder().decode(RuntimeManifest.self, from: data)
    }

    public static func decode(fromFile url: URL) throws -> RuntimeManifest {
        try decode(from: Data(contentsOf: url))
    }

    /// Look up the clip a Claude state resolves to, falling back to the default
    /// state and finally to any clip named `idle`.
    public func clip(forState state: String) -> Clip? {
        if let binding = states[state], let clip = clips[binding.clip] {
            return clip
        }
        if let binding = states[defaultState], let clip = clips[binding.clip] {
            return clip
        }
        return clips["idle"]
    }

    public func binding(forState state: String) -> StateBinding? {
        states[state] ?? states[defaultState]
    }

    /// Effective frames-per-second for a state (respects `fpsOverride`).
    public func fps(forState state: String) -> Double {
        let binding = states[state] ?? states[defaultState]
        if let override = binding?.fpsOverride { return override }
        if let clipID = binding?.clip, let clip = clips[clipID] { return clip.fps }
        return 8
    }

    /// Sanity checks used by tests: every state points at a real clip and every
    /// clip's row/frame counts are in range for the sheet grid.
    public func validate() -> [String] {
        var problems: [String] = []
        if clips[defaultState] == nil && states[defaultState] == nil {
            problems.append("defaultState '\(defaultState)' is not a known state or clip")
        }
        for (name, binding) in states where clips[binding.clip] == nil {
            problems.append("state '\(name)' -> unknown clip '\(binding.clip)'")
        }
        for (name, clip) in clips {
            if clip.row < 0 || clip.row >= sheet.rows {
                problems.append("clip '\(name)' row \(clip.row) out of range 0..<\(sheet.rows)")
            }
            if clip.frameCount < 1 || clip.frameCount > sheet.cols {
                problems.append("clip '\(name)' frameCount \(clip.frameCount) out of range 1...\(sheet.cols)")
            }
        }
        return problems
    }
}
